apiVersion: apps/v1
kind: Deployment
metadata:
  name: why
spec:
  replicas: 1
  selector:
    matchLabels:
      app: why
  template:
    metadata:
      labels:
        app: why
    spec:
      containers:
      - image: okteto.dev/why:latest
        name: why
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "d0a8b74b-2e9f-4a29-9610-3e367fd7a43d"
        - name: Vless_Path
          value: "/s233tikotaoi"
        - name: Vmess_UUID
          value: "d0a8b74b-2e9f-4a29-9610-3e367fd7a43d"
        - name: Vmess_Path
          value: "/s244tikotaoi"
        - name: Share_Path
          value: "/share233"
